name: Build documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r doc_requirements.txt
    - name: Generate documentation
      run: |
        sphinx-build docs docs_out/
        sphinx-build -b doctest docs docs_out/
